[project]
name = "llm-price-calculator"
version = "2025-01"
description = "A price calculator for LLM models and services, using Streamlit."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit>=1.41.1",
]
