[[theme.fontFaces]]
family="Inter"
url="https://fonts.gstatic.com/s/inter/v19/UcCo3FwrK3iLTcviYwYZ8UA3.woff2"
style="normal"
weight="100 900"

[[theme.fontFaces]]
family="Inter"
url="https://fonts.gstatic.com/s/inter/v19/UcCm3FwrK3iLTcvnUwQT9mI1F54.woff2"
style="italic"
weight="100 900"

[theme]
font = "Inter, sans-serif"
headingFont = "Inter, sans-serif"
codeFont = "monospace"

[theme.sidebar]
font = "Inter, sans-serif"
headingFont = "Inter, sans-serif"
codeFont = "monospace"

